// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";

// Optional: if you’re using fonts
// import { Anaheim } from "next/font/google";
// const anaheim = Anaheim({ subsets: ["latin"], weight: ["400", "700"], display: "swap" });

export const metadata = {
	title: "My Next.js App",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			{/* Add a global class or font variable if needed */}
			<body className="min-h-screen bg-[#030528] text-white antialiased">
				{children}
			</body>
		</html>
	);
}
